actors:
  ushisantoasobu:
    image_url: /images/actors/ushisantoasobu.png
    name: ushisantoasobu
    url: https://twitter.com/ushisantoasobu
  hiro:
    image_url: /images/actors/hiro.png
    name: hiro
    url: https://twitter.com/hiro2969
  bob:
    image_url: /images/actors/fukuiretu.png
    name: fukuiretu
    url: https://twitter.com/fukuiretu
author: ushisantoasobu
description: Example description
description_long: Example long description
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: examplehashtag
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Example title
url: http://example.com
